### ISSUE TITLE
Website is now broken

### ISSUE THREAD

**Issue by jp31415926** [Tithen-Firion/Tithen-Firion.github.io#2]
Has been working great, but now the timeline is rendering wrong. See snapshots. This is using Firefox and Chrome.

Firefox 91.0.2:
![image](https://user-images.githubusercontent.com/2908478/131863156-c9cfd29c-ba97-4041-a88d-7dc41b0df26d.png)

Chrome 91.0.4472.164:
![image](https://user-images.githubusercontent.com/2908478/131863223-b64809b6-6d12-4848-b43e-3e40cfe1c4c8.png)

**Comment by Tithen-Firion** [comment]
Works fine here on the newest Firefox and Chrome. It's something on your end.

In Firefox: open <https://tithen-firion.github.io/warframe/poe.html>, press F12, click on the Network tab, check "Disable Cache" and click Reload. This is what I get:
![image](https://user-images.githubusercontent.com/10004135/131895739-3d79c3e7-0f63-4723-89f3-c4f799fe5842.png)

**Comment by jp31415926** [comment]
Same result for me. Firefox I'm running no-script, but Chrome I am not. Both are broken. See below.

Firefox:
![image](https://user-images.githubusercontent.com/2908478/131897601-1ba3988f-dd04-41f8-8ed5-195b87c96364.png)

Chrome:
![image](https://user-images.githubusercontent.com/2908478/131897340-3375678d-d910-4d72-9eaf-23db585be22c.png)

**Comment by jp31415926** [comment]
Interestingly, it appears to be broken on my phone too. I turned off WIFI to force it to use the cellular network (in case there's an issue with my firewall or something) but no difference. I cleared the cache also.

![image](https://user-images.githubusercontent.com/2908478/131898861-6ba4270f-1743-46e1-8999-6a52e1fb5205.png)

**Comment by Tithen-Firion** [comment]
This looks like something's wrong with how your browsers handle CSS. I haven't changed anything in this page in 3 years so it's something on your end. Works fine here on mobile too, both WiFi and cellular:
![image](https://user-images.githubusercontent.com/10004135/131900791-00002e3d-d1a8-4146-96d2-17ec85b7fae4.png)
![image](https://user-images.githubusercontent.com/10004135/131900831-965081fc-bdab-411d-9c6d-356c043ff9a7.png)

Can't reproduce = can't fix. You can try disabling all extensions in your desktop browsers and trying a different mobile browser.

**Comment by jp31415926** [comment]
For some reason the first hour on my pages is 23 instead of 0, and that's what the problem is. That breaks the logic to set the "first" variable and it ends up drawing two date (2nd and 4th) on the first day, and the nothing on the last date.

There is a scrollbar at the bottom of the box where I can scroll over and I can see that the yellow and violet bars are getting pushed over by the second date.

I understand that you have not changed the code, something changed yesterday. I've been using your site for about a week now.

I suspect it will correct itself tomorrow and then show up again in 3 or 6 days.

![image](https://user-images.githubusercontent.com/2908478/131904536-6b78dee9-82ac-462f-85c0-0d70fac153fb.png)

**Comment by jp31415926** [comment]
I fixed this issue by adding an "if (length >0)" in front of the addToContainer call on line 307:

![image](https://user-images.githubusercontent.com/2908478/131907726-3af30058-0b53-48df-b027-0194f20b3a45.png)

Since you don't think there is a bug, I don't know if you want me to send you a push request... I'm happy to. Just let me know.

Thank you for creating this site. It is very handy.

**Comment by Tithen-Firion** [comment]
God dammit, I knew my math was right. Everything fits. But for some reason an element with 0px height makes the last element not fit in the container. That adds the scrollbar which makes the 3rd day element not fit either and wraps it to the second column, messing it up even more.

Feel free to make a PR, you found the solution (I already switched to your timezone and was able to reproduce the problem but you were faster). But add it to line 311 too.

**Comment by jp31415926** [comment]
I'm just glad to help, I sent a PR. I put the second if statement in there as you suggested. Thanks again for the site!
